<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FRAME</name>
   <tag></tag>
   <elementGuidId>a21b95e7-d8b1-4b7f-90b8-cf1fb0bf22e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/frameset/frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/frameset/frame</value>
   </webElementProperties>
</WebElementEntity>
