<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LST_SURVEY_CATEGORY_TIME</name>
   <tag></tag>
   <elementGuidId>3cea1fb9-8dfc-42a7-9d67-24c0a645896c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/div[1]/div[4]/div[1]/a2is-sections[1]/div[2]/div[1]/div[1]/div[1]/a2is-sections[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/a2is-tabs[1]/div[2]/div[2]/div[1]/div[2]/div[2]/a2is-combo-wide-dc[1]/div[2]/div[1]/div[1]/div[1]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[4]/div[1]/a2is-sections[1]/div[2]/div[1]/div[1]/div[1]/a2is-sections[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/a2is-tabs[1]/div[2]/div[2]/div[1]/div[2]/div[2]/a2is-combo-wide-dc[1]/div[2]/div[1]/div[1]/div[1]/button[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FRAME</value>
   </webElementProperties>
</WebElementEntity>
