<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LST_VEHICLE</name>
   <tag></tag>
   <elementGuidId>865594f9-0ede-48f3-b765-f1885147059e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;InquiryTab-1&quot;]/div[1]/div[1]/a2is-combo-wide/div[2]/div[1]/div/div/button[contains(text(),&quot;${policyno}&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;InquiryTab-1&quot;]/div[1]/div[1]/a2is-combo-wide/div[2]/div[1]/div/div/button[contains(text(),&quot;${policyno}&quot;)]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FRAME</value>
   </webElementProperties>
</WebElementEntity>
